# Default configuration for Hybrid Digital Twin
# This file contains the default parameters for training and evaluation

# Physics model configuration
physics_model:
  k: 0.13                    # Degradation coefficient (empirically determined)
  temperature_ref: 25.0      # Reference temperature in Celsius
  
# Machine learning model configuration
ml_model:
  # Network architecture
  hidden_layers: [64, 64]    # Hidden layer sizes
  dropout_rate: 0.1          # Dropout rate for regularization
  activation: "relu"         # Activation function
  output_activation: null    # Output layer activation (null = linear)
  
  # Training parameters
  learning_rate: 0.001       # Adam optimizer learning rate
  batch_size: 32             # Training batch size
  epochs: 100                # Maximum training epochs
  validation_split: 0.2      # Fraction of data for validation
  
  # Regularization
  l1_regularization: 0.0     # L1 regularization strength
  l2_regularization: 0.001   # L2 regularization strength
  
  # Training callbacks
  early_stopping_patience: 10  # Early stopping patience
  reduce_lr_patience: 5        # Learning rate reduction patience
  
  # Optimization
  optimizer: "adam"          # Optimizer type
  loss_function: "mse"       # Loss function

# Data processing configuration
data:
  validation_split: 0.2      # Default validation split
  random_state: 42           # Random seed for reproducibility
  batch_size: 1000           # Batch size for large dataset processing
  
  # Data quality
  outlier_threshold: 3.0     # IQR multiplier for outlier detection
  missing_value_strategy: "interpolate"  # How to handle missing values
  
  # Feature engineering
  add_derived_features: true # Whether to add engineered features
  normalize_features: true   # Whether to normalize input features

# Training configuration
training:
  # Cross-validation
  cv_folds: 5                # Number of cross-validation folds
  cv_scoring: "neg_mean_squared_error"  # CV scoring metric
  
  # Hyperparameter optimization
  hyperopt_trials: 50        # Number of hyperopt trials
  hyperopt_timeout: 3600     # Hyperopt timeout in seconds
  
  # Model selection
  model_selection_metric: "val_rmse"  # Metric for model selection

# Evaluation configuration
evaluation:
  # Metrics to calculate
  metrics:
    - "rmse"
    - "mae" 
    - "r2"
    - "mape"
    - "max_error"
  
  # Statistical tests
  confidence_level: 0.95     # Confidence level for intervals
  bootstrap_samples: 1000    # Bootstrap samples for CI estimation

# Visualization configuration
visualization:
  style: "plotly_white"      # Plotly template
  color_scheme: "default"    # Color scheme
  figure_width: 800          # Default figure width
  figure_height: 600         # Default figure height
  save_format: "png"         # Default save format
  dpi: 300                   # Resolution for saved figures

# Logging configuration
logging:
  level: "INFO"              # Logging level (DEBUG, INFO, WARNING, ERROR)
  format: "structured"       # Log format (structured, simple)
  file_logging: false        # Whether to log to file
  log_file: "logs/hybrid_twin.log"  # Log file path
  max_file_size: "10MB"      # Max log file size
  backup_count: 5            # Number of log file backups

# Monitoring configuration (for production)
monitoring:
  # MLflow tracking
  mlflow:
    tracking_uri: null       # MLflow tracking server URI
    experiment_name: "hybrid_digital_twin"  # Experiment name
    
  # Prometheus metrics
  prometheus:
    enabled: false           # Whether to enable Prometheus metrics
    port: 8001              # Metrics server port
    
  # Model drift detection
  drift_detection:
    reference_window: 1000   # Reference data window size
    detection_window: 100    # Detection window size
    drift_threshold: 0.1     # Statistical drift threshold

# Paths configuration
paths:
  data_dir: "data"           # Base data directory
  models_dir: "models"       # Models directory
  logs_dir: "logs"           # Logs directory
  plots_dir: "plots"         # Plots output directory
  
# Performance configuration
performance:
  # Parallel processing
  n_jobs: -1                 # Number of parallel jobs (-1 = all cores)
  
  # Memory management
  batch_processing: true     # Use batch processing for large datasets
  memory_limit: "4GB"        # Memory limit for batch processing
  
  # GPU acceleration
  use_gpu: false             # Whether to use GPU acceleration
  gpu_memory_limit: null     # GPU memory limit (null = unlimited)

# Reproducibility configuration
reproducibility:
  random_seed: 42            # Global random seed
  deterministic: true        # Whether to use deterministic algorithms
  
# Security configuration
security:
  # Data privacy
  anonymize_data: false      # Whether to anonymize sensitive data
  encrypt_models: false      # Whether to encrypt saved models
  
  # Input validation
  strict_validation: true    # Whether to use strict input validation